steps:
  - name: gcr.io/cloud-builders/gcloud
    id: Decrypt npmrc
    args:
      - kms
      - decrypt
      - --ciphertext-file=npmrc.enc
      - --plaintext-file=/root/.npmrc
      - --location=global
      - --keyring=gcb-keyring
      - --key=npm-key
    volumes:
      - name: home
        path: /root/
  - name: node:current-alpine
    id: Install dependencies
    entrypoint: yarn
    args:
      - install
    env:
      - HOME=/root/
    volumes:
      - name: home
        path: /root/
  - name: node:current-alpine
    id: Set new version
    entrypoint: yarn
    args:
      - version
      - --new-version=$TAG_NAME
      - --no-git-tag-version
  # We have to publish using npm because yarn expects all publishing to go to the public yarnpkg
  # registry. It's a known issue in yarn.
  - name: node:current-alpine
    id: Publish
    entrypoint: npm
    args:
      - publish
    env:
      - HOME=/root/
    volumes:
      - name: home
        path: /root/
