steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - kms
      - decrypt
      - --ciphertext-file=npmrc.enc
      - --plaintext-file=/root/.npmrc
      - --location=global
      - --keyring=gcb-keyring
      - --key=npm-key
    volumes:
      - name: 'home'
        path: /root/
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - kms
      - decrypt
      - --ciphertext-file=yarnrc.enc
      - --plaintext-file=/root/.yarnrc
      - --location=global
      - --keyring=gcb-keyring
      - --key=npm-key
    volumes:
      - name: 'home'
        path: /root/
  - name: 'node:current-alpine'
    entrypoint: yarn
    args: ['install']
    env:
      - HOME=/root/
    volumes:
      - name: 'home'
        path: /root/
  - name: 'node:current-alpine'
    entrypoint: yarn
    args: ['version', '--new-version=$TAG_NAME', '--no-git-tag-version']
    volumes:
      - name: 'home'
        path: /root/
  - name: 'node:current-alpine'
    entrypoint: yarn
    args: ['run', 'build']
  - name: 'node:current-alpine'
    entrypoint: yarn
    args: ['publish', '--non-interactive', '--no-git-tag-version']
    env:
      - HOME=/root/
    volumes:
      - name: 'home'
        path: /root/
